version: 2
jobs:
  build:
    working_directory: ~/snowdrop-automation-client # directory where steps will run
    docker:
    - image: circleci/node:8
    steps:
    - checkout
    - run:
        name: update-npm
        command: 'sudo npm install -g npm@latest'
    - run:
        name: install dependencies
        command: npm install
    - run:
        name: build
        command: npm run build