version: 2
jobs:
  build:
    working_directory: ~/snowdrop-automation-client # directory where steps will run
    docker:
    - image: circleci/node:12
    steps:
    - checkout
    - run:
        name: update-npm
        command: 'sudo npm install -g npm@latest'
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: install dependencies
        command: npm ci
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - ./node_modules
    - run:
        name: install java
        command: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install java 11.0.8.hs-adpt
    - run:
        name: build
        command: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          npm run build
